spring:
  application:
    name: rest-with-spring-boot-and-java
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest_with_spring_boot?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false

cors:
  originPatterns: http://localhost:8080,http://localhost:3000,http://vinifillos.com.br

springdoc:
  paths-to-match: /api/**/v1/**
  swagger-ui:
    use-root-path: true
